name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: SSH Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd ~/app
            git pull origin master
            docker-compose up -d --build
            docker image prune -f
